# This is a basic workflow to help you get started with Actions

name: triggerActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  triggerActions: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correrá
    steps: #Lista de steps del job hola-mundo
      - name: Trigger de detección PR #Segundo step de nombre Hola mundo
        run: echo ¡Trigger ON! #bash
